---
title: "PGIS + ESS WoS Search"
author: "Nan Nourn"
date: "11/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(gt)
options(width = 75)
theme_set(theme_minimal())
myMarkdown <- here("script","pgis_ess_wos.Rmd")
```


```{r message = FALSE, warning = FALSE, fig.align = 'center', fig.dim = c(14,9)}
pgis <- read_csv(here("data", "pgis_ess_wos.csv"))
pgis <- pgis %>%
  mutate(publication_type = as_factor(publication_type),
         publication_name = as_factor(publication_name),
         publication_name = str_to_title(publication_name, locale = "en"),
         published_year = as_factor(published_year),
         total_times_cited_count = as.integer(total_times_cited_count),
         digital_object_identifier = as.character(digital_object_identifier))

pgis %>% 
  filter(publication_type=="J") %>%
  group_by(publication_name) %>%
  count(published_year, count = n()) %>%
  ungroup() %>%
  mutate(publication_name = fct_reorder(publication_name, count)) %>%
  ggplot(aes(publication_name, n, fill = published_year)) +
  geom_col() +
  coord_flip() +
  scale_fill_viridis_d(name = "Year Published",
                       direction = -1) +
  theme(legend.position = "bottom") +
  labs(title = "PGIS + ESS Most Common Journals",
       y = "count",
       x = "publication")

pgis %>% 
  filter(publication_type=="J") %>%
  count(published_year, sort = TRUE) %>%
  ggplot(aes(published_year, n)) +
  geom_col() +
  labs(title = "PGIS + ESS Publications by Year",
       y = "count",
       x = "year")

pgis %>%
  filter(publication_type=="J") %>%
  count(title, publication_name, author, published_year, 
        digital_object_identifier,
        wt = total_times_cited_count, 
        name = "cited", sort = TRUE) %>%
  rename(Title = title,
         Publication = publication_name,
         Authors = author,
         Year = published_year,
         DOI = digital_object_identifier) %>%
  gt() %>%
  tab_header(title = "PGIS + ESS Most Cited Publications")
```
